### ISSUE TITLE
Stuck after Auth Success

### ISSUE THREAD

**Issue by johneyo** [just1and0/React-Native-Paystack-WebView#16]
I get this screen right after a successful authorization and charge
<img width="521" alt="Screenshot 2020-04-22 at 21 02 50" src="https://user-images.githubusercontent.com/36991140/80029924-6bd64780-84df-11ea-9847-2f6ec61f4ba6.png">
Any idea why this is?

Thank you

**Comment by just1and0** [comment]
what version of react-native-webview are you using?

**Comment by johneyo** [comment]
9.2.1

**Comment by just1and0** [comment]
could you use 8.1.2

**Comment by johneyo** [comment]
okay let me try that

**Comment by johneyo** [comment]
The issue still perists

**Comment by just1and0** [comment]
Are you getting any response with the onSuccess callback?

**Comment by johneyo** [comment]
That's the thing, the callback wasn't hit at all. it just gets stuck on that screen

**Comment by johneyo** [comment]
The navigation state where it gets stuck is => 
` {"canGoBack": false, "canGoForward": false, "loading": false, "target": 4029, "title": "Close This Window :: Paystack", "url": "https://standard.paystack.co/close"}`

**Comment by just1and0** [comment]
Please could you use v3.0.1 of the package?

**Comment by Remig9** [comment]
am parsing in my  refNumber but getting another number after successful payment , pls help

**Comment by johneyo** [comment]
> Please could you use v3.0.1 of the package?

Still the same issue when trying the bank auth option

**Comment by just1and0** [comment]
please update to the latest version of the package, all issues have been resolved.

**Comment by nlabofa** [comment]
This issue still persists @just1and0

**Comment by surafelbm** [comment]
@nlabofa any luck fixing this issue? the issue still persists @just1and0 @johneyo

**Comment by mopilo** [comment]
any luck with this issue?
